version: '3'
services: 
    server: 
        build: 
            context: ./server
        environment: 
            - PGDATABASE=postgres
            - PGHOST=db
            - PGUSER=postgres
            - PGPASSWORD=password
            - PGPORT=5432
        entrypoint: npm test
        depends_on: 
            - db
        volumes: 
            - ./server:/app
            - /app/node_modules
    db: 
        build: 
            context: ./test-db
        volumes: 
            - db-test-volume:/var/lib/postgresql/data
volumes: 
    db-test-volume:
